name = "Hugo XML Exporter"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A Hugo theme designed to export an entire Hugo site's content, metadata, and resources into a single, structured XML file."
homepage = "https://github.com/cmahnke/hugo-xml-exporter"
tags = ["export", "xml", "data", "migration", "archive", "headless"]
features = [
  "Exports all regular pages and sections",
  "Preserves content hierarchy (sections and sub-sections)",
  "Includes all front matter parameters (tags, categories, custom fields)",
  "Embeds page content and summary as CDATA (XHTML)",
  "Lists all page resources (images, documents) with metadata (e.g., image dimensions)",
  "Generates a single, well-formed XML file"
]
min_version = "0.141.0"

author = "Christian Mahnke"
author_homepage = "https://christianmahnke.de/"

[mediaTypes]
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.xml-export]
    mediaType = "application/xml"
    baseName = "site-export"
    isPlainText = true
    notAlternative = true
