# theme.toml

name = "Hugo XML Exporter"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A Hugo theme designed to export an entire Hugo site's content, metadata, and resources into a single, structured XML file."
homepage = "https://github.com/your-username/hugo-xml-exporter" # Replace with your actual repository
tags = ["export", "xml", "data", "migration", "archive", "headless"]
features = [
  "Exports all regular pages and sections",
  "Preserves content hierarchy (sections and sub-sections)",
  "Includes all front matter parameters (tags, categories, custom fields)",
  "Embeds page content and summary as CDATA (XHTML)",
  "Lists all page resources (images, documents) with metadata (e.g., image dimensions)",
  "Generates a single, well-formed XML file"
]
min_version = "0.110.0" # Minimum Hugo version required for .Resources and other features

author = "Your Name" # Replace with your name
author_homepage = "https://your-website.com" # Replace with your website